version: '3.8'
name: web-api
services:
    api:
        container_name: web-api
        image: web-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80