version: '3.8'
name: aws-web-api
services:
    api:
        container_name: aws-web-api
        image: aws-web-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80