version: '3.8'
name: awsweb-api
services:
    api:
        container_name: awsweb-api
        image: awsweb-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80